# Generated by Django 4.2.4 on 2023-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
