# Generated by Django 4.2.4 on 2023-10-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_succes',
            field=models.BooleanField(default=False),
        ),
    ]
