# Generated by Django 4.2.4 on 2023-09-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('', ''), ('food', 'Food'), ('drink', 'Drink'), ('fruit', 'Fruit'), ('ice_cream', 'Ice Cream'), ('raw_food', 'Raw Food'), ('man_clothes', 'Man Clothes'), ('man_accesoris', 'Man Accesoris'), ('woman_clothes', 'Woman Clothes'), ('woman_accesoris', 'Woman Accesoris'), ('hat', 'Hat'), ('shoes', 'Shoes'), ('motorcycle_and_accesoris', 'Motorcycle and Accesoris'), ('car_and_accesoris', 'Car and Accesoris'), ('helmet_and_accesoris', 'Helmet and Accesoris'), ('electronic', 'Electronic'), ('handphone_and_accesoris', 'Handphone and Accesoris'), ('laptop_and_accesoris', 'Laptop and Accesoris'), ('computer_and_accesoris', 'Computer and Accesoris'), ('skincare', 'Skincare'), ('makeup', 'Makeup'), ('basic_needs', 'Basic Needs'), ('voucher_and_phonecredit', 'Voucher and Phonecredit'), ('top_up_games', 'Top Up Games'), ('home_decoration', 'Home Decoration')], default='', max_length=50)),
                ('warna', models.TextField(null=True)),
                ('ukuran', models.TextField(null=True)),
                ('rasa', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
