# Generated by Django 4.2.4 on 2023-09-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('', ''), ('food', 'Food'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('vehicles', 'Vehicles and Accessories')], default='', max_length=50)),
                ('warna', models.TextField(null=True)),
                ('ukuran', models.TextField(null=True)),
                ('rasa', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
